name = "cgk"
description = "Computational Geometry Kernel"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded"]

project-files = ["gnat/cgk_primitives.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[configuration.variables]
Float_Size = {type = "Enum", values = ["32", "64"], default = "64"}
SIMD = {type = "Enum", values = ["nosimd", "gcc"], default = "gcc"}
